version: '3.7'
services:
  web:
    build: ./web/
    ports:
    - "8000:8000"

  Database:
    image: postgres:10.2-alpine
    ports:
    - 5432:5432
    environment:
    - POSTGRES_DB=postgres
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=password

