version: '3.7'
services:
  Database:
    container_name: samaj_database
    image: postgres:10.2-alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - database:/var/lib/postgresql/data

  web1:
    build: ./web
    image: samaj_web
    environment:
      - DATABASE_URL=postgresql://postgres:password@samaj_database:5432/postgres
    links:
      - Database
    depends_on:
      - Database

  web2:
    build: ./web
    image: samaj_web
    environment:
    - DATABASE_URL=postgresql://postgres:password@samaj_database:5432/postgres
    links:
    - Database
    depends_on:
    - Database

  Proxy:
    build: ./proxy
    image: samaj_proxy
    ports:
    - "5000:5000"
    environment:
    - WEB1_DNS=http://web1:8000
volumes:
  database:
